"""modifique el atributo de img

Revision ID: aba3bf7caecf
Revises: cc147b78acda
Create Date: 2023-02-26 17:52:36.180368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba3bf7caecf'
down_revision = 'cc147b78acda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
