"""modificacion de domicilio por domisilio

Revision ID: cc147b78acda
Revises: e56aa3be6da5
Create Date: 2023-02-25 16:49:44.049273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc147b78acda'
down_revision = 'e56aa3be6da5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cliente', sa.Column('domisilio', sa.String(), nullable=True))
    op.drop_column('Cliente', 'domiciolio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cliente', sa.Column('domiciolio', sa.VARCHAR(), nullable=True))
    op.drop_column('Cliente', 'domisilio')
    # ### end Alembic commands ###
